version: "3.1"

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: tiny_url
    volumes:
      - db:/data/postgres
      - ./postgres/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    ports:
      - "5432:5432"

volumes:
  db: