CREATE TABLE urls (
    url VARCHAR(10) NOT NULL PRIMARY KEY,
    src_url VARCHAR(200) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);